CREATE DATABASE IF NOT EXISTS vientoenpopa
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE vientoenpopa;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    descripcion TEXT,
    estado TINYINT(1) DEFAULT 1,
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

